# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('conference', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
    ]
